### ISSUE TITLE
How to update some property of CSStickyHeaderParallaxHeader

### ISSUE THREAD

**Issue by sumitjain7** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#88]
I am using CSStickyHeaderParallaxHeader like collectionView.dequeueReusableSupplementaryViewOfKind(CSStickyHeaderParallaxHeader, withReuseIdentifier: "header", forIndexPath: indexPath) as! ProfileHeader;
in viewForSupplementaryElementOfKind method.

I want to get instance of this header cell later in a method to update it. How to do that?
If I again suppose to use "dequeueReusableSupplementaryViewOfKind", I cant because I do not have indexPath there.

**Comment by jamztang** [comment]
I think there are several answer for this reusable cell general question.

First, you should be able to determine the indexPath depending on which of your modal change, because you propagate your table view using your array of modals anyway.


1. ReloadData after modal changes or reloadItemAtIndexPath
2. Use binding patterns (kvo, reactive cocoa, etc)
3. Create an instance variable in your viewController for that reusable view

These should be the general solutions to your question
